/**
 * What an Angular Native app is made of, whichever generator writes it: `@ng-native/nx`'s
 * `application` and `@ng-native/schematics`'s. Both depend on this package already, for the
 * migrations, so the app's shape is written once here rather than once in each.
 *
 * Only what is the same in every workspace lives here: the dependencies and their ranges, the
 * `app.json`, the bundle identifier, the app's `.gitignore`. What a workspace tool changes, and
 * the template files each generator copies, stay with that generator.
 *
 * The source of truth is `template/`, the starter `create-expo-app` uses and the setup this project
 * verifies before every release. The versions below are the template's own, and each generator's
 * `native-app.test.ts` fails the moment they drift from it.
 *
 * The `@ng-native/*` packages are pinned to this package's own version, because every one of them
 * is released in lockstep with it.
 */
const semver = require('semver');

const { version } = require('./package.json');

const FRAMEWORK = [
  '@ng-native/components',
  '@ng-native/device',
  '@ng-native/fabric',
  '@ng-native/metro',
  '@ng-native/platform',
];

/** @type {Record<string, string>} */
const dependencies = {
  ...Object.fromEntries(FRAMEWORK.map((name) => [name, version])),
  '@angular/common': '^22.0.0',
  '@angular/core': '^22.0.0',
  expo: '~57.0.26',
  'expo-status-bar': '~57.0.1',
  'expo-system-ui': '~57.0.4',
  react: '19.2.3',
  'react-native': '0.86.3',
  'react-native-safe-area-context': '~5.7.0',
};

/** @type {Record<string, string>} */
const devDependencies = {
  // An Angular workspace already has Babel 8 through @angular/compiler-cli, and React Native's
  // Babel peer would otherwise take the newest copy there is.
  // The typecheck script compiles the templates too, which only the Angular compiler can.
  '@angular/compiler-cli': '^22.0.0',
  '@babel/core': '^7.29.7',
  '@ng-native/testing': version,
  '@types/react': '~19.2.2',
  typescript: '~6.0.3',
  vitest: '^5.0.0',
};

/**
 * The app's own `.gitignore`: the lines of the template's that are about the app's directory. The
 * rest, `node_modules/` and the like, are the workspace's business.
 */
const GITIGNORE = [
  '# generated native folders',
  '/ios',
  '/android',
  '',
  "# Generated by @ng-native/tailwind's withTailwind, rebuilt on every Metro start",
  '.angular-native/',
  '',
].join('\n');

/** Java's reserved words, which Android refuses as a segment of a package name. */
const JAVA_KEYWORDS = new Set(
  (
    'abstract assert boolean break byte case catch char class const continue default do double ' +
    'else enum extends false final finally float for goto if implements import instanceof int ' +
    'interface long native new null package private protected public return short static ' +
    'strictfp super switch synchronized this throw throws transient true try void volatile while'
  ).split(' '),
);

/**
 * Kotlin's hard keywords, which it refuses as a package segment as Java refuses its own: Expo
 * writes the Android package into `MainActivity.kt` and `MainApplication.kt` without escaping one.
 */
const KOTLIN_KEYWORDS = new Set(
  (
    'as break class continue do else false for fun if in interface is null object package return ' +
    'super this throw true try typealias typeof val var when while'
  ).split(' '),
);

/** Whether `segment` is a keyword Java or Kotlin refuses as a package segment. */
const isKeyword = (segment) => JAVA_KEYWORDS.has(segment) || KOTLIN_KEYWORDS.has(segment);

/**
 * Whether iOS takes `id` as a bundle identifier and Android as a package name: two or more
 * segments, each a letter and then letters or digits (iOS refuses `_`, Android `-`), none of them
 * a Java or Kotlin keyword.
 *
 * @param {string} id
 */
function isBundleIdentifier(id) {
  const segments = id.split('.');
  return segments.length > 1 && segments.every((s) => /^[a-z][a-z0-9]*$/i.test(s) && !isKeyword(s));
}

/**
 * Why `id` cannot be the app's bundle identifier, as a sentence, or `undefined` when it can.
 *
 * @param {string} id
 */
function bundleIdentifierProblem(id) {
  if (isBundleIdentifier(id)) return undefined;
  return (
    `${id} is not a bundle identifier both iOS and Android accept: ` +
    'two or more dot-separated segments, each a letter and then letters or digits, none a Java or ' +
    'Kotlin keyword.'
  );
}

/**
 * `com.<scope>.<name>`, for an app given no `--bundleIdentifier`, where prebuild would otherwise
 * make it `com.anonymous.<name>`. The scope is left out when it cannot be made a segment.
 *
 * @param {string} name the app's name, without a scope
 * @param {string | undefined} scope the workspace's npm scope, `@acme`
 */
function bundleIdentifier(name, scope) {
  const clean = (text) => text.toLowerCase().replace(/[^a-z0-9]/g, '');
  const valid = (segment) => /^[a-z]/.test(segment) && !isKeyword(segment);
  const org = clean(scope ?? '');
  const app = clean(name);
  return ['com', ...(valid(org) ? [org] : []), valid(app) ? app : `app${app}`].join('.');
}

/**
 * The template's `app.json`, named for this app, without the template's icons: they are the
 * template's branding, and Expo draws its own default until `icon` is set.
 *
 * @param {string} name the project name, which is also the Expo slug once any scope is removed
 * @param {string} [id] the iOS bundle identifier and Android package, by default one from `name`
 */
function appJson(name, id) {
  const slug = name.replace(/^@[^/]+\//, '');
  const bundle = id ?? bundleIdentifier(slug, name.match(/^@[^/]+/)?.[0]);
  const expo = {
    name: slug,
    slug,
    version: '1.0.0',
    // Not left to Expo, which adds `web` whenever `react-dom` resolves, and @nx/react puts one there.
    platforms: ['ios', 'android'],
    orientation: 'portrait',
    userInterfaceStyle: 'automatic',
    ios: { supportsTablet: true, bundleIdentifier: bundle },
    android: { package: bundle, predictiveBackGestureEnabled: false },
    scheme: slug.replace(/[^a-z0-9]/gi, '').toLowerCase(),
    // The template's: Expo otherwise guesses a router root from src/app and says so on every start.
    extra: { router: { root: 'src/app' } },
    plugins: ['@ng-native/metro'],
  };
  return JSON.stringify({ expo }, null, 2) + '\n';
}

/**
 * The dependencies an app lists in its own `package.json`, at the ranges the workspace root
 * installs, though nothing installs from it.
 *
 * All of them, because Expo's autolinking links the native modules the app's `package.json` names
 * and no others: without `react-native-safe-area-context` here, Android crashed on RNCSafeAreaView.
 * And `expo prebuild`, which `expo run:ios` starts with, adds `expo`, `react` or `react-native` if
 * it does not find them and then offers to install them into the app's directory, which would put a
 * second copy of React Native beside the root's.
 *
 * @param {{ dependencies?: Record<string, string>, devDependencies?: Record<string, string> }} root
 */
function prebuildPins(root) {
  const installed = { ...root.devDependencies, ...root.dependencies };
  return Object.fromEntries(
    Object.keys(dependencies).map((pkg) => [pkg, installed[pkg] ?? dependencies[pkg]]),
  );
}

/**
 * Where what a workspace already has can be older than what a new app is given: `@ng-native/testing`
 * installs Vitest 5 but its plugin runs on 4, which `ng new` 22.1 and the Nx preset still start on.
 * The range here is that package's `vitest` peer, and a test holds the two together.
 */
const accepted = { vitest: '^4.0.8 || ^5.0.0' };

/**
 * Why an existing dependency would stop this app installing or running, as a sentence each.
 *
 * Only ranges already in the manifest are judged, and only a range that cannot overlap the one
 * wanted is a conflict: `~6.0.2` and `~6.0.3` resolve to the same TypeScript. A missing package is
 * added at the version above. Nothing is rewritten, because moving a workspace's Angular or Vitest
 * is an upgrade of every project in it, and that belongs to `ng update` or `nx migrate`, not to a
 * generator.
 *
 * @param {{ dependencies?: Record<string, string>, devDependencies?: Record<string, string> }} manifest
 * @returns {string[]}
 */
function conflicts(manifest) {
  const existing = { ...manifest.dependencies, ...manifest.devDependencies };
  const problems = [];
  for (const [name, installed] of Object.entries({ ...dependencies, ...devDependencies })) {
    const range = existing[name];
    const wanted = accepted[name] ?? installed;
    if (!range || name.startsWith('@ng-native/')) continue;
    if (semver.validRange(range) && !semver.intersects(range, wanted)) {
      problems.push(
        `${name} is ${range} here, and Angular Native needs ${wanted}. ` +
          `npm will refuse the install until it is moved.`,
      );
    }
  }
  return problems;
}

module.exports = {
  dependencies,
  devDependencies,
  GITIGNORE,
  appJson,
  bundleIdentifier,
  isBundleIdentifier,
  bundleIdentifierProblem,
  prebuildPins,
  accepted,
  conflicts,
};
